### ISSUE TITLE
Can we make People easily linkable in Prose.io?

### ISSUE THREAD

**Issue by tmtmtmtm** [mysociety/kuvakazim#112]
Can we make it easy to link to things like People or Parties from prose.io — e.g. in http://prose.io/#mysociety/kuvakazim/edit/master/info/political-parties.md ?

**Comment by chrismytton** [comment]
Ooh, yes that should be pretty trivial, just a case of adding the collections to [`prose_io_links.rb`](https://github.com/mysociety/kuvakazim/blob/master/_plugins/prose_io_links.rb).

**Comment by tmtmtmtm** [comment]
Yay. That's what I had hoped the answer would be :)
