### ISSUE TITLE
Design breaking on mobile

### ISSUE THREAD

**Issue by chrismytton** [mysociety/kuvakazim#121]
Safari on iPhone 5S with iOS 9.2

![img_3703](https://cloud.githubusercontent.com/assets/22996/12290356/39337ba2-b9d9-11e5-9049-74499ca543cf.PNG)

**Comment by JenMysoc** [comment]
Also on tablets and android phones:

![screenshot_20160113-162449](https://cloud.githubusercontent.com/assets/4170351/12319622/73f4c8f0-ba9b-11e5-9aa4-a7f6a2fca535.png)

![screenshot_20160113-144019](https://cloud.githubusercontent.com/assets/4170351/12319628/7f609c32-ba9b-11e5-80ec-d875a446377b.png)

Tablet is Nexus 9 running Marshmallow and phone is Nexus 5X running Marshmallow

The breaking design for these seems to be mainly around the logo - It doesn't resize where the box does.

**Comment by wrightmartin** [comment]
Weirdly thought I fixed that bug...

**Comment by wrightmartin** [comment]
Yeah, getting it on my android too, will fix it today

**Comment by wrightmartin** [comment]
Worked it out finally, android doesn't support the use of `background-size` in the shorthand version of the `background` property. Fix incoming

**Comment by chrismytton** [comment]
@wrightmartin Will that also fix the iOS issue?

**Comment by wrightmartin** [comment]
@chrismytton just testing now

**Comment by chrismytton** [comment]
:+1:

**Comment by wrightmartin** [comment]
@chrismytton Yep, all fixed
![screen shot 2016-01-14 at 11 10 45](https://cloud.githubusercontent.com/assets/2292925/12322947/7e70c590-baaf-11e5-8fc2-28647dedd17c.png)

**Comment by chrismytton** [comment]
Woohoo!
