### ISSUE TITLE
Move build to Travis

### ISSUE THREAD

**Issue by chrismytton** [mysociety/kuvakazim#15]
We want to be able to use plugins with jekyll for generating data, but GitHub pages doesn't work with plugins. It would also be good to use Jekyll 3 as it builds complex sites _much_ faster (as an example this site builds in 82s with Jekyll 2.4.0, 6s with Jekyll 3.0.1).

So as part of this I'd like to move the actual building of the site to Travis. I've chosen travis over Heroku for this as arguably the static files are just a build artifact. Having it on Travis also means that the webhook receiver on Heroku simply needs to create a new commit updating the popolo url that we want to use, which it can get from the `countries.json` payload, then Travis will handle the rest.
- [x] Move over to using the `master` branch for jekyll files
- [x] Add travis build for the project that runs for the `master` branch and builds it to the `gh-pages` branch
- [x] Add a README to `gh-pages` warning that it's an automatically generated branch
- [x] Add a README to the `master` branch which explains how this all works

**Comment by chrismytton** [comment]
Some useful links:
- https://gist.github.com/domenic/ec8b0fc8ab45f39403dd
- http://benlimmer.com/2013/12/26/automatically-publish-javadoc-to-gh-pages-with-travis-ci/

**Comment by dracos** [comment]
https://github.com/mysociety/theyworkforyou/commit/5267f8a3165ef81edd6a2b142fe9ad6f8e51e905 might be useful too :)

**Comment by chrismytton** [comment]
@dracos Ah yes that does look handy, thanks!
