### ISSUE TITLE
Refresh design for Kuvakazim

### ISSUE THREAD

**Issue by wrightmartin** [mysociety/kuvakazim#50]
Placeholder ticket.
## Browser usage for Zimbabwe

Massive Opera mini penetration
Rough split between Chrome, Firefox and IE on desktop
IE11 and 8 are mostly used versions of IE

![statcounter-browser-zw-monthly-201411-201511](https://cloud.githubusercontent.com/assets/2292925/11588818/3bc3c0ca-9a7b-11e5-9f5a-f04d1d31fc5c.png)
![statcounter-browser_version_partially_combined-zw-monthly-201411-201511](https://cloud.githubusercontent.com/assets/2292925/11588776/f58bf668-9a7a-11e5-9818-e90e5e22e95e.png)
![statcounter-browser_version_partially_combined-zw-monthly-201411-201511 1](https://cloud.githubusercontent.com/assets/2292925/11588777/f70dd754-9a7a-11e5-975c-1f3431eb71f6.png)

**Comment by chrismytton** [comment]
@wrightmartin Are you happy to call this done now?

**Comment by wrightmartin** [comment]
Yep!
