### ISSUE TITLE
All office holders on Ministry pages

### ISSUE THREAD

**Issue by tmtmtmtm** [mysociety/kuvakazim#52]
Currently the [Minister of Finance page](http://staging.kuvakazim.com/executive_positions/minister-of-finance/) only lists Patrick Chinamasa. It should also list Tendai Biti.

**Comment by tmtmtmtm** [comment]
@chrismytton I couldn't work out how to get this data, and tied myself in knots trying to work out how to even examine what information was being passed to the page.

**Comment by chrismytton** [comment]
@tmtmtmtm It looks like Tendai Biti isn't in the Popolo file - https://raw.githubusercontent.com/everypolitician/everypolitician-data/kuvakazim/data/Zimbabwe/Assembly/ep-popolo-v1.0.json, but they are in the people tab of the spreadsheet.

Looking at the popolo there seems to be 219 Assembly people + 65 Senate people, so 294 total. However there are 336 people in the spreadsheet, so we've lost 42 people somewhere along the way.

**Comment by tmtmtmtm** [comment]
@chrismytton We're currently only including members of Term 8 in the Popolo, and Tendai Biti is only listed as a member of Term 5. I'm a little reluctant to include such piecemeal information directly into EP: if we're going to have a Term, I'd rather have _all_ the members for that term, rather than just five of them (or, in the case of the Senate, only a single one). 

So, I think there are two different issues here:

1) Generally, the Executive plugin (and others) needs to be able to cope with people who are (or have been) Executive members, but who were never members of the Legislature.

2) We need to get better data for historic terms, or extend the concept of EP slightly to allow us to include significantly more incomplete data. (And probably change what gets displayed on EveryPolitician.org to show Terms that have more than a certain % of members)

**Comment by chrismytton** [comment]
Ok so looking into this a bit more there does appear to be a problem with the executive pages - [Fungai J Majome](http://staging.kuvakazim.com/assembly/person/9466549d-52e6-4365-a732-651da9cb9303/) has a link to [Deputy Minister of Women Affairs, Gender and Community Development](http://staging.kuvakazim.com/executive_positions/deputy-minister-of-women-affairs-gender-and-community-development/) but she doesn't appear on that page.

So in terms of KuvakaZim we need to do the following:
- [ ] Make sure all position holders appear on the executive pages
- [ ] Show people that don't have a legislative membership on the executive pages

The we also need to make a separate decision about whether we want to add incomplete data to EP, but that's probably for another ticket.

**Comment by tmtmtmtm** [comment]
Yep — that sounds like a good plan.
