### ISSUE TITLE
Generating the search box is slow

### ISSUE THREAD

**Issue by chrismytton** [mysociety/kuvakazim#54]
Removing [this line from `header.html`](https://github.com/mysociety/kuvakazim/blob/7fd2f85e058aff8ea645f8c83235efda4bed0fbf/_includes/header.html#L14) cuts the build time of the site in half. We need to find an alternative way of generating the search box that doesn't slow the build down so much.

**Comment by tmtmtmtm** [comment]
Ideally the search would include lots of other information about people, parties etc too (other names, common misspellings, etc — similar to, but even more extended than, the country_selector in EP's Viewer-Sinatra). So I'm guessing we should generate a suitable datastructure somewhere in rubyland that has all the relevant info in a format that can be dumped straight in with minimal jekyll-land processing.
