### ISSUE TITLE
Some pages look a bit bare

### ISSUE THREAD

**Issue by chrismytton** [mysociety/kuvakazim#63]
![screen shot 2015-12-11 at 17 21 06](https://cloud.githubusercontent.com/assets/22996/11750511/9ae30c22-a02b-11e5-9f69-6dbb301b5b18.png)

http://staging.kuvakazim.com/assembly/person/53db868e-8ecf-4e5a-9bcd-86811afc6bf1/

These pages have no information about a person, and therefore only have a comment box, leaving them looking a bit empty.

@wrightmartin @zarino Any ideas about how we could improve these pages?

**Comment by chrismytton** [comment]
This is looking slightly less bare now _most_ people have the summary section added in #69 

![screen shot 2015-12-14 at 14 51 00](https://cloud.githubusercontent.com/assets/22996/11784059/3661a7ce-a272-11e5-832e-71d1dfede933.png)

**Comment by wrightmartin** [comment]
We could move the meta information from the sidebar into the main content, they seem to be generally well populated

**Comment by chrismytton** [comment]
@wrightmartin Yep that seems like a good idea. The other related issue on the person page is that there's a (variable?) amount of whitespace that appears above the persons name.

**Comment by wrightmartin** [comment]
@chrismytton the white space is related to the profile picture. 

I tried to fix it without rewriting the layout completely but couldn't. If we take this further, a rewrite of quite a lot of the old pombola styles would fix that problem, and many others

**Comment by chrismytton** [comment]
@wrightmartin Ah cool, in that case don't worry about it :)
