### ISSUE TITLE
Styling for WriteInPublic button on person page

### ISSUE THREAD

**Issue by chrismytton** [mysociety/kuvakazim#90]
Need to make the WriteInPublic link that was added in https://github.com/mysociety/kuvakazim/pull/89 look a little bit better…

![screen shot 2015-12-17 at 20 23 11](https://cloud.githubusercontent.com/assets/22996/11881012/1592f7c8-a4fc-11e5-9bfa-9503d0403a34.png)

**Comment by chrismytton** [comment]
This button has been temporarily hidden in https://github.com/mysociety/kuvakazim/pull/96, so you'll need to remove the `disabled` option from `_config.yml` in order to get the button to show up.

**Comment by wrightmartin** [comment]
Done in #100
